version: '{build}'
image: Visual Studio 2017
platform:
- x86
- x64
environment:
  matrix:
  - CONDA: 36
install:
- ps: |
    git submodule update -q --init --recursive
    if ($env:CONDA -eq "27") { $env:CONDA = "" }
    if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
    $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
    conda config --set always_yes yes --set changeps1 no
    conda config --add channels conda-forge
    conda update -q conda
    conda install -q conda-build
build_script:
- ps: |
    conda build conda.recipe
test_script:
- ps: python tests\test.py